# menu
GAME_NAME = 'TODO: LD40 Game'
TITLE_SIZE = 80
TITLE_COLOR = (182,165,121)
MESSAGE_SIZE = 54
MESSAGE_COLOR = (142,128,165)
ITEM_SIZE = 48
ITEM_COLOR = (255, 255, 255)

# in-game texts
INGAME_TEXT_SIZE = 36
INGAME_TEXT_COLOR = (0,0,0)

# resources
PROJECT_ROOT = 'ld40_setup'
RESOURCES_ROOT = 'resources'
IMAGES_DIR = 'images'
SOUNDS_DIR = 'sounds'
LEVELS_DIR = 'levels'

# screen setting
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1000
FPS = 30

# player speed
PLAYER_SPEED = 500  # px/second

# number of tiles on the
TILE_SIZE = 50
TILES = (20, 10)

# max camera acc
GAME_CAMERA_VELOCITY = 50
MAX_GAME_CAMERA_DISTANCE = 150

# train
TRAIN_DELAY = 0.25  # second

# particles
LIGHT_PARTICLE_BATCH_SIZE = 3
LIGHT_PARTICLE_COUNT = 48
LIGHT_PARTICLE_SPEED = 20
LIGHT_PARTICLE_LIFETIME = 15
LIGHT_PARTICLE_ANGLE = 16

# soundwaves
SOUNDWAVE_MOD = 10
SOUNDWAVES_COUNT = 20

# floor items
FLOOR_ITEM_PROBABILITY = 1
